<?php

use App\Enums\TemplateMappingKind;
use App\Enums\TemplateDocumentType;

return [
    'upload_disk' => env('TEMPLATE_UPLOAD_DISK', 'local'),

    'max_upload_kb' => 5120,

    'allowed_extensions' => [
        TemplateDocumentType::GradingSheet->value => ['xlsx', 'xls', 'xlsm'],
        TemplateDocumentType::Sf9->value => ['xlsx', 'xls', 'xlsm'],
        TemplateDocumentType::Sf10->value => ['xlsx', 'xls', 'xlsm'],
    ],

    'definitions' => [
        TemplateDocumentType::GradingSheet->value => [
            ['field_key' => 'school_year_name', 'label' => 'School Year', 'description' => 'Displays the school-year label on the grading sheet.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value]],
            ['field_key' => 'grading_period_label', 'label' => 'Grading Period', 'description' => 'Displays the quarter or grading-period label.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value]],
            ['field_key' => 'grade_level_name', 'label' => 'Grade Level', 'description' => 'Displays the grade level assigned to the section.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value]],
            ['field_key' => 'section_name', 'label' => 'Section', 'description' => 'Displays the section name for the teaching load.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value]],
            ['field_key' => 'subject_name', 'label' => 'Subject Name', 'description' => 'Displays the subject name for the export.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value]],
            ['field_key' => 'teacher_name', 'label' => 'Teacher Name', 'description' => 'Displays the teacher assigned to the load.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value]],
            ['field_key' => 'adviser_name', 'label' => 'Adviser Name', 'description' => 'Displays the adviser assigned to the section.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value]],
            ['field_key' => 'learner_name_column', 'label' => 'Learner Name Column', 'description' => 'Starting cell or named range for learner names.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value]],
            ['field_key' => 'learner_lrn_column', 'label' => 'Learner LRN Column', 'description' => 'Starting cell or named range for LRNs.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value]],
            ['field_key' => 'learner_sex_column', 'label' => 'Learner Sex Column', 'description' => 'Starting cell or named range for learner sex values.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value]],
            ['field_key' => 'learner_grade_column', 'label' => 'Quarterly Grade Column', 'description' => 'Starting cell or named range for final quarterly grades.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value]],
            ['field_key' => 'learner_remarks_column', 'label' => 'Remarks Column', 'description' => 'Starting cell or named range for grade remarks.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value]],
        ],
        TemplateDocumentType::Sf9->value => [
            ['field_key' => 'school_name', 'label' => 'School Name', 'description' => 'Maps the school information area on the report card.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value, TemplateMappingKind::MergedCellTarget->value, TemplateMappingKind::SheetAnchorBased->value]],
            ['field_key' => 'school_year_name', 'label' => 'School Year', 'description' => 'Maps the school-year area on the report card.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value, TemplateMappingKind::MergedCellTarget->value, TemplateMappingKind::SheetAnchorBased->value]],
            ['field_key' => 'grading_period_label', 'label' => 'Grading Period', 'description' => 'Maps the grading period or quarter label when the template uses one explicit display area.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value, TemplateMappingKind::SheetAnchorBased->value]],
            ['field_key' => 'grade_level_name', 'label' => 'Grade Level', 'description' => 'Maps the learner grade level area.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value, TemplateMappingKind::SheetAnchorBased->value]],
            ['field_key' => 'section_name', 'label' => 'Section', 'description' => 'Maps the learner section area.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value, TemplateMappingKind::SheetAnchorBased->value]],
            ['field_key' => 'learner_name', 'label' => 'Learner Name', 'description' => 'Maps the learner identity area. CARD-style templates may use a split name group instead of one cell.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value, TemplateMappingKind::SplitFieldGroup->value]],
            ['field_key' => 'learner_lrn', 'label' => 'Learner LRN', 'description' => 'Maps the learner LRN area.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value, TemplateMappingKind::SheetAnchorBased->value]],
            ['field_key' => 'adviser_name', 'label' => 'Adviser Name', 'description' => 'Maps the adviser or class adviser area.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value, TemplateMappingKind::SheetAnchorBased->value]],
            ['field_key' => 'subject_name_column', 'label' => 'Subject Name Column', 'description' => 'Maps learner subject rows. CARD-style templates may use a structured subject block instead of one flat column.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value, TemplateMappingKind::SubjectTableBlock->value]],
            ['field_key' => 'subject_grade_column', 'label' => 'Subject Grade Column', 'description' => 'Maps approved subject grades. CARD-style templates may use a structured subject block instead of one flat column.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value, TemplateMappingKind::SubjectTableBlock->value]],
            ['field_key' => 'subject_remarks_column', 'label' => 'Subject Remarks Column', 'description' => 'Maps subject remarks when the workbook exposes them explicitly.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value, TemplateMappingKind::SubjectTableBlock->value]],
            ['field_key' => 'general_average', 'label' => 'General Average', 'description' => 'Maps the general-average area. CARD-style templates may use semester-specific anchor-based areas.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value, TemplateMappingKind::SheetAnchorBased->value]],
            ['field_key' => 'promotion_remarks', 'label' => 'Promotion Remarks', 'description' => 'Maps promotion, disposition, or equivalent remarks only when the workbook exposes that area.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value, TemplateMappingKind::SheetAnchorBased->value]],
        ],
        TemplateDocumentType::Sf10->value => [
            ['field_key' => 'school_name', 'label' => 'School Name', 'description' => 'Maps school-identification areas for the permanent record.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value, TemplateMappingKind::SheetAnchorBased->value, TemplateMappingKind::RepeatingRowBlock->value]],
            ['field_key' => 'learner_name', 'label' => 'Learner Name', 'description' => 'Maps the learner identity area. SF10 templates may split the name across dedicated cells.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value, TemplateMappingKind::SplitFieldGroup->value]],
            ['field_key' => 'learner_lrn', 'label' => 'Learner LRN', 'description' => 'Maps the learner LRN area.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value, TemplateMappingKind::SheetAnchorBased->value]],
            ['field_key' => 'grade_level_name', 'label' => 'Grade Level', 'description' => 'Maps the grade-level area or scholastic-record block area.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value, TemplateMappingKind::SheetAnchorBased->value, TemplateMappingKind::RepeatingRowBlock->value]],
            ['field_key' => 'school_year_name', 'label' => 'School Year', 'description' => 'Maps the school-year area or scholastic-record block area.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value, TemplateMappingKind::SheetAnchorBased->value, TemplateMappingKind::RepeatingRowBlock->value]],
            ['field_key' => 'section_name', 'label' => 'Section', 'description' => 'Maps the section area or scholastic-record block area.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value, TemplateMappingKind::SheetAnchorBased->value, TemplateMappingKind::RepeatingRowBlock->value]],
            ['field_key' => 'adviser_name', 'label' => 'Adviser Name', 'description' => 'Maps the adviser area or scholastic-record block area.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value, TemplateMappingKind::SheetAnchorBased->value, TemplateMappingKind::RepeatingRowBlock->value]],
            ['field_key' => 'learner_status', 'label' => 'Year-End Status', 'description' => 'Maps learner disposition only when the workbook has a structural target for it.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value, TemplateMappingKind::SheetAnchorBased->value]],
            ['field_key' => 'general_average', 'label' => 'General Average', 'description' => 'Maps the general-average area when the workbook exposes one.', 'required' => false, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value, TemplateMappingKind::SheetAnchorBased->value, TemplateMappingKind::RepeatingRowBlock->value]],
            ['field_key' => 'subject_name_column', 'label' => 'Subject Name Column', 'description' => 'Maps the scholastic-record learning-area rows. Real SF10 workbooks may use repeating row blocks across multiple sheets.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value, TemplateMappingKind::RepeatingRowBlock->value]],
            ['field_key' => 'final_rating_column', 'label' => 'Final Rating Column', 'description' => 'Maps the final-rating rows or repeating scholastic blocks.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value, TemplateMappingKind::RepeatingRowBlock->value]],
            ['field_key' => 'action_taken_column', 'label' => 'Action Taken Column', 'description' => 'Maps the action-taken / remarks rows or repeating scholastic blocks.', 'required' => true, 'default_mapping_kind' => TemplateMappingKind::FixedCell->value, 'allowed_mapping_kinds' => [TemplateMappingKind::FixedCell->value, TemplateMappingKind::NamedRange->value, TemplateMappingKind::RepeatingRowBlock->value]],
        ],
    ],
];
