<x-app-layout>
    <x-slot name="header">
        <x-page-header
            eyebrow="Registrar verification"
            :title="$record['document_type']['label'].' Verification'"
            description="Read-only verification for a finalized official learner record. This page surfaces version, template, and audit metadata without reopening or editing any workflow state."
        >
            <x-slot name="actions">
                <a href="{{ route('registrar.records.learners.show', ['learner' => $record['learner_id']]) }}" class="ui-link-button">
                    Learner history
                </a>
                <a href="{{ route('registrar.records.index') }}" class="ui-link-button">
                    Repository
                </a>
            </x-slot>
        </x-page-header>
    </x-slot>

    <div class="page-stack">
        <section class="grid gap-4 lg:grid-cols-3">
            <x-section-panel title="Record verification summary" class="lg:col-span-2">
                <div class="flex flex-wrap gap-2">
                    <x-status-chip :tone="$record['document_type']['tone']">
                        {{ $record['document_type']['label'] }}
                    </x-status-chip>
                    <x-status-chip :tone="$record['finalization_status']['tone']">
                        {{ $record['finalization_status']['label'] }}
                    </x-status-chip>
                </div>

                <dl class="mt-5 grid gap-4 md:grid-cols-2">
                    <div>
                        <dt class="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">Learner</dt>
                        <dd class="mt-2 text-sm font-semibold text-slate-900">{{ $record['learner_name'] }}</dd>
                        <dd class="mt-1 text-sm text-slate-500">LRN: {{ $record['lrn'] }}</dd>
                    </div>
                    <div>
                        <dt class="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">School context</dt>
                        <dd class="mt-2 text-sm font-semibold text-slate-900">{{ $record['school_year_name'] }}</dd>
                        <dd class="mt-1 text-sm text-slate-500">{{ $record['grade_level_name'] }} · {{ $record['section_name'] }}</dd>
                    </div>
                    <div>
                        <dt class="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">Record metadata</dt>
                        <dd class="mt-2 text-sm font-semibold text-slate-900">{{ $record['period_label'] }}</dd>
                        <dd class="mt-1 text-sm text-slate-500">Version {{ $record['record_version'] }} · Template {{ $record['template_name'] }} · v{{ $record['template_version'] }}</dd>
                    </div>
                    <div>
                        <dt class="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">Generation and finalization</dt>
                        <dd class="mt-2 text-sm font-semibold text-slate-900">Generated {{ $record['generated_at'] ?? 'Unknown' }}</dd>
                        <dd class="mt-1 text-sm text-slate-500">Generated by {{ $record['generated_by'] }}</dd>
                        <dd class="mt-2 text-sm font-semibold text-slate-900">Finalized {{ $record['finalized_at'] ?? 'Unknown' }}</dd>
                        <dd class="mt-1 text-sm text-slate-500">Finalized by {{ $record['finalized_by'] }}</dd>
                    </div>
                </dl>
            </x-section-panel>

            <x-section-panel title="Workflow context" description="These values are read-only and come from the finalized official record payload and linked workflow metadata.">
                <dl class="mt-5 space-y-4">
                    @foreach ($workflowContext as $item)
                        <div>
                            <dt class="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">{{ $item['label'] }}</dt>
                            <dd class="mt-2 text-sm text-slate-700">{{ $item['value'] }}</dd>
                        </div>
                    @endforeach
                </dl>
            </x-section-panel>
        </section>

        <x-table-wrapper title="Source Subject Rows" description="Persisted subject data carried by the finalized official record.">
            <div class="overflow-x-auto">
                <table class="data-table">
                    <thead>
                        <tr>
                            <th>Subject</th>
                            <th>Grade / Rating</th>
                            <th>Remarks</th>
                            <th>Action taken</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($subjectRows as $row)
                            <tr>
                                <td class="font-semibold text-slate-900">{{ $row['subject_name'] }}</td>
                                <td>{{ $row['grade_value'] !== '' ? $row['grade_value'] : 'Not stored' }}</td>
                                <td>{{ $row['remarks'] ?? 'Not stored' }}</td>
                                <td>{{ $row['action_taken'] ?? 'Not stored' }}</td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="4">
                                    <x-empty-state title="No subject rows were stored with this record." description="This finalized version did not persist any subject-row payload data." />
                                </td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </x-table-wrapper>

        <section class="grid gap-6 xl:grid-cols-2">
            <x-table-wrapper title="Version History" description="Finalized versions for this learner and document type.">
                <div class="overflow-x-auto">
                    <table class="data-table">
                        <thead>
                            <tr>
                                <th>Version</th>
                                <th>Context</th>
                                <th>Finalized</th>
                                <th class="text-right">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($versionHistory as $historyRecord)
                                <tr>
                                    <td>
                                        <p class="font-semibold text-slate-900">Version {{ $historyRecord['record_version'] }}</p>
                                        @if ($historyRecord['is_current'])
                                            <p class="table-note text-emerald-700">Current view</p>
                                        @endif
                                    </td>
                                    <td>
                                        <p class="font-semibold text-slate-900">{{ $historyRecord['school_year_name'] }}</p>
                                        <p class="table-support">{{ $historyRecord['section_name'] }} · {{ $historyRecord['period_label'] }}</p>
                                    </td>
                                    <td>{{ $historyRecord['finalized_at'] ?? 'Unknown' }}</td>
                                    <td class="text-right">
                                        @if (! $historyRecord['is_current'])
                                            <div class="table-row-actions ml-auto w-fit">
                                                <x-table-action-button
                                                    :href="route('registrar.records.show', ['report_card_record' => $historyRecord['id']])"
                                                    icon="eye"
                                                    title="Verify official record version"
                                                    aria-label="Verify official record version"
                                                >
                                                Verify
                                                </x-table-action-button>
                                            </div>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </x-table-wrapper>

            <x-section-panel title="Audit Timeline" description="Existing workflow events already recorded for this official record.">
                <div class="divide-y divide-slate-200">
                    @forelse ($auditTimeline as $event)
                        <div class="px-4 py-4">
                            <div class="flex flex-wrap items-center gap-2">
                                <x-status-chip tone="slate">{{ $event['action_label'] }}</x-status-chip>
                                <span class="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">{{ $event['occurred_at'] ?? 'Unknown time' }}</span>
                            </div>
                            <p class="mt-2 text-sm font-semibold text-slate-900">{{ $event['actor'] }}</p>
                            @if (filled($event['remarks']))
                                <p class="mt-2 text-sm text-slate-600">{{ $event['remarks'] }}</p>
                            @endif
                        </div>
                    @empty
                        <div class="px-4 py-10 text-center text-sm text-slate-500">
                            No audit events were available for this finalized record.
                        </div>
                    @endforelse
                </div>
            </x-section-panel>
        </section>
    </div>
</x-app-layout>
